tunnel: mcp-server-tunnel
credentials-file: /Users/nickarndt/Code/mcp-http-server/.cloudflared/credentials.json

ingress:
  - hostname: mcp-server-839650329042.us-central1.run.app
    service: https://mcp-server-839650329042.us-central1.run.app
    originRequest:
      noHappyEyeballs: true
      http2Origin: true
      disableChunkedEncoding: false
      keepAliveConnections: 10
      keepAliveTimeout: 90s
  - service: http_status:404
